window.GameHubAvatars = [
  { id: 1, name: "Nova", label: "A1", persona: "Balanced beginner AI", color: "#fbbf24", src: "assets/avatar1.png", url: "assets/avatar1.png" },
  { id: 2, name: "Rex", label: "A2", persona: "Slightly aggressive", color: "#f97316", src: "assets/avatar2.webp", url: "assets/avatar2.webp" },
  { id: 3, name: "Kira", label: "A3", persona: "Gets risky but lucky", color: "#ef4444", src: "assets/avatar3.webp", url: "assets/avatar3.webp" },
  { id: 4, name: "Jett", label: "A4", persona: "Loves trick cards", color: "#3b82f6", src: "assets/avatar4.webp", url: "assets/avatar4.webp" },
  { id: 5, name: "Orion", label: "A5", persona: "Logical and strategic", color: "#22c55e", src: "assets/avatar5.webp", url: "assets/avatar5.webp" },
  { id: 6, name: "Blitz", label: "A6", persona: "Completely random", color: "#a855f7", src: "assets/avatar6.webp", url: "assets/avatar6.webp" },
  { id: 7, name: "Skye", label: "A7", persona: "Calm and defensive", color: "#14b8a6", src: "assets/avatar7.webp", url: "assets/avatar7.webp" },
  { id: 8, name: "Vex", label: "A8", persona: "Aggressive player", color: "#eab308", src: "assets/avatar8.webp", url: "assets/avatar8.webp" },
  { id: 9, name: "Lyra", label: "A9", persona: "Unpredictable", color: "#f43f5e", src: "assets/avatar9.webp", url: "assets/avatar9.webp" },
  { id: 10, name: "Echo", label: "A10", persona: "Uses skips and reverses", color: "#38bdf8", src: "assets/avatar10.webp", url: "assets/avatar10.webp" },
  { id: 11, name: "Sol", label: "A11", persona: "Strategic color control", color: "#84cc16", src: "assets/avatar11.png", url: "assets/avatar11.png" },
  { id: 12, name: "Mira", label: "A12", persona: "Takes risky plays", color: "#d946ef", src: "assets/avatar12.webp", url: "assets/avatar12.webp" },
  { id: 13, name: "Atlas", label: "A13", persona: "Plays smart combos", color: "#f59e0b", src: "assets/avatar13.webp", url: "assets/avatar13.webp" },
  { id: 14, name: "Rune", label: "A14", persona: "Loves wild cards", color: "#60a5fa", src: "assets/avatar14.webp", url: "assets/avatar14.webp" },
  { id: 15, name: "Vale", label: "A15", persona: "Defensive play", color: "#10b981", src: "assets/avatar15.webp", url: "assets/avatar15.webp" },
  { id: 16, name: "Nyx", label: "A16", persona: "Smart long-game", color: "#fb7185", src: "assets/avatar16.webp", url: "assets/avatar16.webp" },
  { id: 17, name: "Pyre", label: "A17", persona: "Aggressive draw card", color: "#c084fc", src: "assets/avatar17.webp", url: "assets/avatar17.webp" },
  { id: 18, name: "Sage", label: "A18", persona: "Strategic and patient", color: "#facc15", src: "assets/avatar18.webp", url: "assets/avatar18.webp" },
  { id: 19, name: "Cora", label: "A19", persona: "Color master", color: "#4ade80", src: "assets/avatar19.webp", url: "assets/avatar19.webp" },
  { id: 20, name: "Apex", label: "A20", persona: "Master-level AI", color: "#93c5fd", src: "assets/avatar20.webp", url: "assets/avatar20.webp" }
];
