window.GameHubThemes = [
  { id: 1, name: "Classic Arena", price: 0, src: "assets/themes/theme1.webp", url: "assets/themes/theme1.webp" },
  { id: 2, name: "Rich Velvet", price: 300, src: "assets/themes/theme2.webp", url: "assets/themes/theme2.webp" },
  { id: 3, name: "Neon Edge", price: 350, src: "assets/themes/theme3.webp", url: "assets/themes/theme3.webp" },
  { id: 4, name: "Soft Gradient", price: 400, src: "assets/themes/theme4.webp", url: "assets/themes/theme4.webp" },
  { id: 5, name: "Glassy Surface", price: 450, src: "assets/themes/theme5.webp", url: "assets/themes/theme5.webp" },
  { id: 6, name: "Gold Accent", price: 500, src: "assets/themes/theme6.webp", url: "assets/themes/theme6.webp" },
  { id: 7, name: "Cosmic Glow", price: 550, src: "assets/themes/theme7.webp", url: "assets/themes/theme7.webp" },
  { id: 8, name: "Frosted Glow", price: 600, src: "assets/themes/theme8.webp", url: "assets/themes/theme8.webp" },
  { id: 9, name: "Ember Glow", price: 650, src: "assets/themes/theme9.webp", url: "assets/themes/theme9.webp" },
  { id: 10, name: "Ultra Clean", price: 700, src: "assets/themes/theme10.webp", url: "assets/themes/theme10.webp" },
  { id: 11, name: "Neon Circuit", price: 750, src: "assets/themes/theme11.webp", url: "assets/themes/theme11.webp" },
  { id: 12, name: "Aurora Silk", price: 800, src: "assets/themes/theme12.webp", url: "assets/themes/theme12.webp" },
  { id: 13, name: "Shadow Rune", price: 850, src: "assets/themes/theme13.webp", url: "assets/themes/theme13.webp" },
  { id: 14, name: "Prism Edge", price: 900, src: "assets/themes/theme14.webp", url: "assets/themes/theme14.webp" },
  { id: 15, name: "Energy Ring", price: 950, src: "assets/themes/theme15.webp", url: "assets/themes/theme15.webp" },
  { id: 16, name: "Crystal Frame", price: 1000, src: "assets/themes/theme16.webp", url: "assets/themes/theme16.webp" },
  { id: 17, name: "Galaxy Orbit", price: 1100, src: "assets/themes/theme17.webp", url: "assets/themes/theme17.webp" },
  { id: 18, name: "Royal Pattern", price: 1200, src: "assets/themes/theme18.webp", url: "assets/themes/theme18.webp" },
  { id: 19, name: "Liquid Light", price: 1300, src: "assets/themes/theme19.webp", url: "assets/themes/theme19.webp" },
  { id: 20, name: "Infinity Core", price: 1500, src: "assets/themes/theme20.webp", url: "assets/themes/theme20.webp" }
];
